#!/bin/sh

DIR="/cygdrive/c/CodeBlocksProjects/OurGame"
SYS="B3n's Desktop"


if [ $# = 3 ]; then

if [ x"$2" = x-m ]; then
	MSG=$3
fi

elif [ $# = 4 ]; then

if [ x"$3" = x-m ]; then
        MSG=$4
fi

else
        MSG=""
fi





if [ x"$1" = x-sync ]; then
	cd $DIR
	
	if [ x"$2" = x-test ]; then
		git pull git@github.com:b3ngr33ni3r/Magnet.git test
		git add ./*
		git commit -m  "pushed from $SYS @ $(date "+%H:%M:%S on %m/%d/%y")."
		git push git@github.com:b3ngr33ni3r/Magnet.git test
		
	else
		git pull git@github.com:b3ngr33ni3r/Magnet.git master
		git add ./*
		git commit -m  "pushed from $SYS @ $(date "+%H:%M:%S on %m/%d/%y")."
		git push git@github.com:b3ngr33ni3r/Magnet.git master
		
	fi

elif [ x"$1" = x-pull ]; then
	cd $DIR
	
	if [ x"$2" = x-release ]; then
		git pull git@github.com:b3ngr33ni3r/Magnet.git release
		
	elif [ x"$2" = x-test ]; then
		git pull git@github.com:b3ngr33ni3r/Magnet.git test
		
	else
		git pull git@github.com:b3ngr33ni3r/Magnet.git master	
	fi
	
elif [ x"$1" = x-push ]; then
	cd $DIR
	
	git add ./*
	git commit -m  "pushed from $SYS @ $(date "+%H:%M:%S on %m/%d/%y")."
	
	if [ x"$2" = x-release ]; then
		git push git@github.com:b3ngr33ni3r/Magnet.git release
	
	elif [ x"$2" = x-test ]; then
		git push git@github.com:b3ngr33ni3r/Magnet.git test
		
	else
		git push git@github.com:b3ngr33ni3r/Magnet.git master
	fi
	
elif [ x"$1" = x-cd ]; then
	echo $DIR
	
elif [ x"$1" = x-init ]; then
	cd $DIR
	
	chmod -R 777 .
	
	rm -R *
	rm -R .git
	
	git init
	Magnet -pull
	
else

	echo "-sync		Pulls then pushes from GitHub, syncing the project."
	echo "   -test		Pulls then pushes from GitHub test branch to local system ."	
	echo "-pull		Pulls from GitHub, downloading the project."
	echo "   -release	Pull from GitHub release branch to local system ."
	echo "   -test		Pull from GitHub test branch to local system ."
	echo "-push		Pushes from local system to GitHub, uploading the project."
	echo "   -release	Push from local system to GitHub release branch."	
	echo "   -test		Push from local system to GitHub test branch."
	echo "-cd		Echos the directory for the local Magnet project."
	echo "-init		Removes local directory & re-pulls file from the project."
	echo "-m "MESSAGE"	Sets the begining of the commit message for the project."	

fi

#
# This command syncs the Magnet github project (localdir<->github/Magnet)
#

